"""adicionar subcategoria a Categorias

Revision ID: c3aca17408b7
Revises: 0eb43c1b6c68
Create Date: 2026-07-14 11:57:52.648722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3aca17408b7'
down_revision: Union[str, Sequence[str], None] = '0eb43c1b6c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('cat_subcategoria', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'cat_subcategoria')
    # ### end Alembic commands ###
